# Numpy

python
- 단점 : 속도가 느림
- 파이썬을 compile할 수 있다.
- glue language : 어느 언어와도 잘 붙는다.


- pypy : 파이썬으로 만든 파이썬, 파이썬보다 5배정도 빠르고 문법 수정 할 필요가 없다. 

numpy - 다른 빠른 것들도 있지만 numpy가 제일 쉽다.
1. 속도 빠르다
2. 편하고 쉽다
-   c로 만들었고 데이터 구조가 vectorization을 사용하므로 빠르다



#### c로 만들어짐 , vectorization
#### 효율적인 자료구조 - homogenous, 일렬로 저장하고 stride로 표현하기 때문

Vectorization
---
- 계산이 간단하고 속도가 빨라진다.
- numpy는 gpu를 지원하지 않는다. 따라서 gpu 지원하는 기능을 numpy에 추가해준다.
- loop가 없음 -> 속도가 느려지기 때문에, for를 사용하면 성능이 떨어짐 => for를 쓰지않고 연산하는 것을 vectorization(array programming)이라 한다.
- 큰 범위에서는 좋지만 , 작은 범위에서는 효율성이 떨어진다.



list형태로 나오므로 mutable 하다. 따라서 mutable의 문제점을 모두 가지고 있다.

-  class이므로 instance화 가능
-  ndim, len()으로 차원을 확인할 수 있다.
-  좀 더 자세하게 알고 싶다면 shape을 사용

사칙연산 가능(elementwise방식)

stride를 통해 효과적으로 데이터에 접근 할 수 있다.

- 0으로 초기화하고 싶을 때에는 np.zeros((x,y))
- 1은 np.ones((x,y))
- 원하는 숫자로 초기화 하고싶을땐 np.full((3,2),6)


a = np.arange(27).reshape(3,3,3)

# Fancy Indexing


- Column값 뽑을때 유용

In [3]:
import numpy as np
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

In [5]:
a = np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
a[1,3:5]

array([8, 9])

In [25]:
a[:,4]

array([ 4,  9, 14, 19, 24])

In [26]:
a[-2: , -2:]

array([[18, 19],
       [23, 24]])

# broadcasting

- numpy 자체에서 자동적으로 크기 맞춰주는 것
- 크기가 너무 커지면 에러가 난다.

In [27]:
a + 3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [6]:
a*3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57],
       [60, 63, 66, 69, 72]])

# ufunc

- 범용적으로 사용할 수 있는 함수 (벡터, 스칼라 다 가능)
- 여러 개 동시에 계산 가능
- numpy를 쓰면 편하게 사용 할 수 있다.

abs([-1,2,3])

In [29]:
#ex)
np.abs([-1,2,3])

array([1, 2, 3])

# copy

- 파이썬에서 copy를하면 swallow copy이지만 numpy에서는 deep copy이다
- 원본을 보관하기 위해서 copy를 한다.
- numpy에서 shallow copy를 하고 싶으면 view() 함수를 쓴다.

In [36]:
a = np.arange(10).reshape(2,5)

In [37]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**numpy에서는 copy()함수는 deep copy이다.**

In [38]:
b=a.copy()

In [39]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
a[0][0] = 2100

In [42]:
#b는 deep copy가 되었음을 알 수 있다.
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**view()를 이용하여 swallow copy를 해준다.**

In [44]:
c= a.view()

In [45]:
c

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [46]:
a

array([[2100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

# resize와 reshape의 차이


- resize는 mutable이고 함수를 불러오면 구조가 바뀐다.
- reshape를 호출하면 구조가 변하지 않고 결과만 보여진다.

In [50]:
a = np.arange(27)

In [51]:
a.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [52]:
a.reshape((3,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [64]:
b= a.reshape(3,9).copy()

In [65]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [66]:
b.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [67]:
#b는 바뀌지 않음
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [62]:
b.resize(9,3)

In [63]:
#b가 바뀜 inplace=True가 되어버림
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [71]:
# reshape로 바꾸고 싶다면 재할당을 해주어야한다.
a = a.reshape(3,9)

In [72]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

# split

**a는 바뀌지 않는다.**

In [75]:
np.split(a,(1,2))
# 0-1까지 , 1-2까지, 2-끝까지

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [77]:
np.split(a,(2,2))
#0<=a<2,  2<=a<2 (없음) ,  2<=a

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [78]:
np.split(a,(2,5))
#0<=a<5 ,  2<=a<5, 5이후 없음 []

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [80]:
np.split(a,(1,3))
#0<=a<1 ,  1<=a<3, 3<=a

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

**axis를 이용한 split**

In [82]:
np.split(a,(5,5), axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

**hsplit**  
axis=1 한것이 hsplit

In [87]:
np.hsplit(a,(5,))

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

**vsplit**  
axis=0 한것이 vsplit

In [93]:
np.vsplit(a,(9,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

## stack
